version: "3.9"
volumes:
        iql981-db-vol: {}
services:
        iql981-db:
                build:
                        context: .
                        dockerfile: Dockerfile_db
                ports:
                        - "3306:3306"
                volumes:
                - iql981-db-vol:/var/lib/mysql
        iql981-api:
                depends_on:
                        - iql981-db
                build:
                        context: .
                        dockerfile: Dockerfile_api
                ports:
                        - "8080:8080"