---
build-job:
  stage: build
  script:
    - echo "Building project..."
    - npm i

unit-test-job:
  stage: test
  needs: [build-job]
  script:
    - echo "Running unit tests..."
    - npm install mocha
    - npm test

curl-test-job:
  stage: test
  script:
    - echo "Running CURL tests..."

deploy-job:
  stage: deploy
  script:
    - echo "if we made it to this point then all tests passed OR none yet exist :)"
    - echo "Deploying to class server..."
    - echo "$GITLAB_KEY" > ./private_key
    - chmod 400 ./private_key
    - ssh -i ./private_key iql981@10.100.201.3 "cd ~/cs-4783-devops-project; git pull origin assignment3; pm2 reload startup"
    - rm ./private_key
...
