apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iql981-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20M
  storageClassName: "manual"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iql981-db-deployment
  labels:
    app: iql981-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iql981-db
  template:
    metadata:
      labels:
        app: iql981-db
    spec:
      containers:
        - name: iql981-db-c
          image: blopez01/iql981-db
          ports:
            - containerPort: 3306
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: iql981-db-vol
      volumes:
        - name: iql981-db-vol
          persistentVolumeClaim: 
            claimName: iql981-pvc